export const storeProducts = [
    {
        id: 1,
        title: "iPhone 12 Pro R MAX X S",
        img: "img/iphone.png",
        price: "$1200",
        company: "GOOGLE",
        info:
            "Miss Patel's all time favourite Apple iPhone's latest high end model. The best camera setup available to capture your beautiful self. (don't know why it's so expensive tho)",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 2,
        title: "Mercedes AMG GT",
        img: "img/merc.png",
        price: "$200k",
        company: "SAMSUNG",
        info:
            "Miss Patel's Mercedes Benz. The perfect blend of elegance and performance with class leading luxurious interiors and safety standards to keep you safe and sound.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 3,
        title: "MacBook Pro",
        img: "img/macbook.png",
        price: "$2000",
        company: "htc",
        info:
            "Apple's top of the line Laptop with powerful hardware and software. Intense processing power packed inside a sleek package so that you can take it with yourself easily on your many trips around the world.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 4,
        title: "Dentist things",
        img: "img/dentist.png",
        price: "no idea",
        company: "htc",
        info:
            "Don't know what its called. It's for when you become the best orthodontist in the world.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 5,
        title: "Some Expensive Chanel Bag",
        img: "img/bag.png",
        price: "$9999999",
        company: "htc",
        info:
            "An overpriced bag from Chanel in Miss Patel's favourite colour. ",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 6,
        title: "A Big Home",
        img: "img/house.png",
        price: "$3M, maybe?",
        company: "apple",
        info:
            "A big cozy home in the suburbs with a private gym, home theater and everything you'll ever need. Because you deserve the best, sir.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 7,
        title: "Laura Mercier Stuff",
        img: "img/lauramercier.png",
        price: "$999999",
        company: "apple",
        info:
            "The best beauty products for the best person, not that you need any of it.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 8,
        title: "Expensive Prada Dress",
        img: "img/dress.png",
        price: "$9999999",
        company: "apple",
        info:
            "A beautiful dress for Miss Patel. Perfectly tailored to show off your hotness. (I DON'T support it but you like it so why not xD)",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 9,
        title: "Grey's Anatomy Complete CDs",
        img: "img/greys.jpg",
        price: "$10",
        company: "apple",
        info:
            "Miss Patel's all time favourite show's CDs so that you can watch it anytime, anywhere.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 10,
        title: "A Trip to Europe",
        img: "img/trip.png",
        price: "$30k",
        company: "apple",
        info:
            "An exquisite trip to Miss Patel's favourite travel destinations. All around Europe including all the small and big attractions with the best hotels. Complimentary Tickets and arrangements for someone else you would want to take along (me pls). Also including a few extra days to explore on your own.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 11,
        title: "Overpriced Louis Vuittons",
        img: "img/shoes.png",
        price: "$9999",
        company: "apple",
        info:
            "Sophisticated and tasteful women's shoe things in blue (don't know what they're called), Miss Patel's favourite colour. For when you feel like torturing your feet.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 12,
        title: "Cute Little Puppy",
        img: "img/puppy.png",
        price: "$0",
        company: "apple",
        info:
            "Adopting a cute little puppy like Miss Patel always wanted. A trusty companion and a bundle of joy to lighten up the place.",
        inCart: false,
        count: 0,
        total: 0,
    },
];

export const detailProduct = {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 10,
    company: "google",
    info:
        "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
};
